spring:
  application:
    name: api-gateway
server:
  port: 60012
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1112/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hello-service
  filter:
    root: Spring_Cloud\api-gateway-dynamic-filter\src\main\java\com\duofei\filter
    interval: 5