spring:
  redis:
    host: 192.168.3.148
    port: 6379
  datasource:
    username: mysqlhxf
    password: mysqlhxf123456
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai