spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoKr9527/duofei.git
          search-paths: Spring_Cloud/config-file
          username:
          password:
server:
  port: 60020