spring:
  application:
    name: duofei
  profiles:
    active: dev,test
  cloud:
    config:
      server:
        git:
          # 在这里不需要密码，可能是因为我在git 命令行窗口访问时，已经输入了密码和账户，
          uri: https://gitee.com/duofei/config-server
          skip-ssl-validation: true
          timeout: 5
          basedir: E:\GitHub\config-local
  security:
    user:
      name: duofei
      password: duofei001
server:
  port: 60020