server:
  port: 8082
spring:
  application:
    name: feign-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1112/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
  maxAutoRetries: 2
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
