server:
  port: 18085
    #tomcat:
    #最小线程数
    #min-spare-threads: 5
    #最大线程数
    #max-threads: 10
    #当达到最大线程数时，能够接受最大的等待数
    #accept-count: 1
spring:
  application:
    name: sentinel-app
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        heartbeat-interval-ms: 10000
        port: 8720
      eager: true
      filter:
        enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        network-interface: eth9
        namespace: ecbbf883-5744-42e3-b448-09aabee90d7f
feign:
  sentinel:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: nacos-discovery,sentinel
