#provider 环境
dubbo:
  application:
    name: dubbo-study
  protocol:
    name: dubbo
    port: 21810
  provider:
    register: true
    registry:
      protocol: zookeeper
      address: zookeeper://192.168.1.3:2181
  config:
    override: true
spring:
  main:
    allow-bean-definition-overriding: true