dubbo:
  application:
    name: dubbo-study
  protocol:
    name: dubbo
    port: 21811
  provider:
    register: false
  config:
    override: true
  consumer:
    registry:
      protocol: zookeeper
      address: zookeeper://192.168.3.18:2181
spring:
  main:
    allow-bean-definition-overriding: true