server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    # 由于该应用为注册中心，设置为false ，代表不向注册中心注册自己
    register-with-eureka: false
    # 不需要去检索服务
    fetch-registry: false
  server:
    enable-self-preservation: false