server:
  port: 1113
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1112/eureka/
  server:
    my-url: http://localhost:1113/
    enable-self-preservation: false
spring:
  application:
    name: eureka-server-node2
