spring:
  application:
    name: hello-service
eureka:
  client:
    service-url:
      machine1: http://localhost:1113/eureka/
    region: djz
    availability-zones:
      djz: machine1
server:
  servlet:
    context-path: /provider