spring:
  application:
    name: api-gateway
server:
  port: 60010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1112/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hello-service
    api-b:
      path: /api-b/**
      serviceId: feign-consumer