spring:
 datasource:
  url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
  username: root
  password: root
  druid:
   url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
   username: root
   password: root
   initial-size: 5
  other:
    url: jdbc:mysql://localhost:3306/springbootother?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    initial-size: 5
    filters: stat
  jpa:
   database: mysql
   show-sql: true
   hibernate:
   ddl-auto: update
 cache:
  cache-names: cache1,cache2
server:
 port: 8080
 servlet:
  context-path: /sp