server:
  port: 18086
spring:
  application:
    name: sentinel-app
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        heartbeat-interval-ms: 10000
        port: 8721
      eager: true
      filter:
        enabled: false
management:
  endpoint:
    sentinel:
      enabled: true
